### ISSUE TITLE
Determinar los objetivos de la organización

### ISSUE THREAD

**Issue by aasitimb** [aasitimb/AP1_Repositorio#1]
En esta tarea se deberá mantener una reunión con los stakeholders del proyecto a fin de establecer los objetivos del mismo.

Tareas involucradas:

- [x] Mantener una reunión entre todos los involucrados para obtener los objetivos del negocio con este proyecto.

**Comment by XavierMedinaMacias** [comment]
**Objetivos:**

- Desarrollar un modelo predictivo basado en técnicas de ciencia de datos con una efectividad mínima del 80% que permita estimar la probabilidad de mora de nuevos créditos otorgados por la entidad financiera. 

- Identificar anticipadamente aquellos créditos con mayor riesgo de incumplimiento, permitiendo a la organización implementar estrategias preventivas y de mitigación para minimizar el impacto financiero.
